import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.scss";
import CustomCursor from "@/components/ui/customCursor/CustomCursor";
import Layout from "@/components/layout/Layout";

const geistAudioWide = localFont({
  src: "./fonts/Audiowide-Regular.ttf",
  variable: "--font-audiowide-sans",
  weight: "400",
  style: "normal",
});
const geistRobotoMono = localFont({
  src: "./fonts/RobotoMono-VariableFont_wght.ttf",
  variable: "--font-robotoMono-mono",
  weight: "100 900",
});
const geistInter = localFont({
  src: "./fonts/Inter-VariableFont_opsz,wght.ttf",
  variable: "--font-inter-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistAudioWide.variable} ${geistRobotoMono.variable} ${geistInter.variable} antialiased`}
      >
        <Layout>{children}</Layout>
        <CustomCursor/>
      </body>
    </html>
  );
}
